version: '3.8'

services:
  book_catalog:
    build: ./book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  inventory_management:
    build: ./inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}