apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
  labels:
    app: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: book-catalog
        image: $CONTAINER_REGISTRY_BOOK/book_catalog:$VERSION
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:E5OJuKRE14iotwfsvHwJeqsjaKK1eKmO@dpg-cq0nb2aju9rs73b0500g-a.oregon-postgres.render.com/part2"
      - name: inventory-management
        image: $CONTAINER_REGISTRY_INVENTORY/inventory_management:$VERSION
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:E5OJuKRE14iotwfsvHwJeqsjaKK1eKmO@dpg-cq0nb2aju9rs73b0500g-a.oregon-postgres.render.com/part2"

---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer