name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  
  workflow_dispatch:

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensures CD only runs after a successful CI

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Staging
      env:
        CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}
        IMAGE_TAG: ${{ github.sha }}
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > $HOME/.kube/config
        kubectl set image deployment/my-deployment my-container=${CONTAINER_REGISTRY}/my-app:${IMAGE_TAG} --namespace=staging

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      env:
        CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}
        IMAGE_TAG: ${{ github.sha }}
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > $HOME/.kube/config
        kubectl set image deployment/my-deployment my-container=${CONTAINER_REGISTRY}/my-app:${IMAGE_TAG} --namespace=production